### PR TITLE
Implemented materialize-style input-boxes.

### PR DESCRIPTION
**Pull request by moritzuehling**
Hey!

I really like this project, and would love to work on it in the future. Currently however I dislike the design, it's very old-school, basically like every other IRC-client. 

I'd like to go on a new modern route, and get a design that is inspired by Gitter and Slack, which are really pleasing to the eye. 

I'm thinking if we can make the design switchable - that's something HTML / CSS would be great for, since you should be able to just load another stylesheet. 

However, sometimes a little JavaScript is required to make it look great (in this pull-request because you can't switch on "has text" in CSS).

However, most animations (like the one in this pull-request) can be done entirely in CSS, so that should be good.

### CODE REVIEW

**Comment by josegonzalez** [comment]
:+1:

**Comment by J3RN** [comment]
FWIW, I agree on your ideas for modernizing the design :+1:

**Comment by noraesae** [comment]
Sorry that I couldn't put much attention on this. Will check soon!

**Comment by anirbanmu** [comment]
Looks great!

**Pull request closed without merging**
